##  1. Importing the Packages

In [1]:
import numpy as np

In [2]:
np.set_printoptions( suppress = True , linewidth = 100 , precision = 2)

## 2. Importing the Data

In [3]:
raw_data = np.genfromtxt('loan-data.csv' , delimiter = ';', autostrip = True , skip_header = 1)
raw_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## 3. Checking for Incomplete Data

In [4]:
np.isnan(raw_data).sum()

88005

In [5]:
temporary_fill = np.nanmax(raw_data) + 1
temporary_fill

68616520.0

In [6]:
mean_fill = np.nanmean(raw_data, axis = 0)
mean_fill

C:\Users\quang\AppData\Local\Temp\ipykernel_6440\4134642545.py:1: RuntimeWarning: Mean of empty slice
  mean_fill = np.nanmean(raw_data, axis = 0)


array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [7]:
review = np.array([
    np.nanmin(raw_data, axis = 0),
    np.nanmean(raw_data, axis = 0),
    np.nanmax(raw_data, axis = 0)
])
review

C:\Users\quang\AppData\Local\Temp\ipykernel_6440\2203968480.py:2: RuntimeWarning: All-NaN slice encountered
  np.nanmin(raw_data, axis = 0),
C:\Users\quang\AppData\Local\Temp\ipykernel_6440\2203968480.py:3: RuntimeWarning: Mean of empty slice
  np.nanmean(raw_data, axis = 0),
C:\Users\quang\AppData\Local\Temp\ipykernel_6440\2203968480.py:4: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data, axis = 0)


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [8]:
raw_data.shape[1]


14

## 4. Splitting the Dataset

### Splitting the Columns

In [9]:
string_col_index = np.argwhere(np.isnan(mean_fill) == True ).squeeze()
string_col_index

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [10]:
num_col_index = np.argwhere(np.isnan(mean_fill) == False ).squeeze()
num_col_index

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

### Re-importing the Dataset

In [11]:
num_data = np.genfromtxt('loan-data.csv' , delimiter = ';', autostrip = True , skip_header = 1
                        , usecols = num_col_index,
                        filling_values = temporary_fill)
num_data

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [12]:
str_data = np.genfromtxt('loan-data.csv' , delimiter = ';', autostrip = True , skip_header = 1
                        , usecols = string_col_index,
                         dtype = np.str
                        )
str_data

C:\Users\quang\AppData\Local\Temp\ipykernel_6440\2460505278.py:3: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str


array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### The Names of the Columns

In [13]:
header_full = np.genfromtxt('loan-data.csv' , delimiter = ';', autostrip = True , skip_footer = raw_data.shape[0],
                          dtype = np.str)
header_full

C:\Users\quang\AppData\Local\Temp\ipykernel_6440\2661546099.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str)


array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [14]:
header_num = header_full[num_col_index]
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [15]:
header_str = header_full[string_col_index]
header_str

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

## Creating Checkpoints:

In [16]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [17]:
checkpoint_test = checkpoint('checkpoint-test', header_str , str_data)
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

## 5. Manipulating String Columns

In [18]:
header_str

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [19]:
header_str[0] = 'issue date'
header_str

array(['issue date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

### Issue Date

In [20]:
np.unique(str_data[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [21]:
str_data[:,0] = np.chararray.strip(str_data[:,0], '-15')
print(str_data[:,0])

['May' '' 'Sep' ... 'Jun' 'Apr' 'Dec']


In [22]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [23]:
for i in range(13):
        str_data[:,0] = np.where(str_data[:,0] == months[i],
                                          i,
                                          str_data[:,0])

In [24]:
str_data[:,0].sort()
np.unique(str_data[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan Status

In [25]:
np.unique(str_data[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [26]:
bad_status = np.array(['','Charged Off', 'Default', 'Late (31-120days)'])

In [27]:
str_data[:,1] = np.where(np.isin(str_data[:,1] , bad_status),
                                          0,
                                          1)

In [28]:
np.unique(str_data[:,1])

array(['0', '1'], dtype='<U69')

### Term

In [29]:
np.unique(str_data[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [30]:
str_data[:,2] = np.chararray.strip(str_data[:,2],' months')

In [31]:
np.unique(str_data[:,2])

array(['', '36', '60'], dtype='<U69')

In [32]:
str_data[:,2] = np.where ( str_data[:,2] == '', '60' , str_data[:,2])

In [33]:
np.unique(str_data[:,2]) 

array(['36', '60'], dtype='<U69')

### Grade and Subgrade

In [34]:
np.unique(str_data[:,3]) [1:]

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [35]:
np.unique(str_data[:,4] , return_counts = True) 

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([514, 285, 278, 239, 323, 502, 509, 517, 530, 553, 494, 629, 567, 586, 564, 423, 391, 267,
        250, 255, 223, 235, 162, 171, 139, 114,  94,  52,  34,  43,  16,  19,  10,   3,   7,   2],
       dtype=int64))

#### Filling Sub Grade

In [36]:
for i in np.unique(str_data[:,3])[1:]:
    str_data[:,4] = np.where((str_data[:,4] == '') & (str_data[:,3] == i),
                                      i + '5',
                                      str_data[:,4])

In [37]:
np.unique(str_data[:,4] , return_counts = True) 

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [38]:
    str_data[:,4] = np.where((str_data[:,4] == '') ,
                                      'H1',
                                      str_data[:,4])

In [39]:
np.unique(str_data[:,4] , return_counts = True) 

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9],
       dtype=int64))

#### Removing Grade

In [40]:
str_data = np.delete(str_data , 3 , axis = 1)

In [41]:
str_data[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [42]:
header_str = np.delete( header_str, 3 )

In [43]:
header_str

array(['issue date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

#### Converting Sub Grade

In [44]:
np.unique(str_data[:,3]).shape[0]

36

In [45]:
keys = list(np.unique(str_data[:,3]))                         
values = list(range(1, np.unique(str_data[:,3]).shape[0] + 1)) 
dict_sub_grade = dict(zip(keys, values))

In [46]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [47]:
for i in np.unique(str_data[:,3]):
        str_data[:,3] = np.where(str_data[:,3] == i, 
                                          dict_sub_grade[i],
                                          str_data[:,3])

In [48]:
dict_sub_grade['G5']

35

### Verification Status

In [49]:
np.unique(str_data[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [50]:
str_data[:,4] = np.where((str_data[:,4] == '') | (str_data[:,4] == 'Not Verified') ,
                                      0,
                                      1)

In [51]:
np.unique(str_data[:,4])

array(['0', '1'], dtype='<U69')

### URL

In [52]:
np.unique(str_data[:,5])

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994'], dtype='<U69')

In [53]:
str_data[:,5] = np.chararray.strip(str_data[:,5] , 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [54]:
np.unique(str_data[:,5])

array(['12606806', '13026045', '1312426', ..., '8138291', '8214572', '849994'], dtype='<U69')

In [55]:
str_data[:,5].astype(np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [56]:
num_data[:,0].astype(np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [57]:
np.array_equal(str_data[:,5].astype(np.int32) , num_data[:,0].astype(np.int32))

True

In [58]:
str_data = np.delete(str_data , 5 , axis = 1)
header_str = np.delete(header_str , 5)

In [59]:
str_data[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [60]:
header_str

array(['issue date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

### State Address

In [61]:
np.unique(str_data[:,5] , return_counts = True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [62]:
state_name , state_count = np.unique(str_data[:,5] , return_counts = True)

In [63]:
state_count_sorted = np.argsort (-state_count)
state_count_sorted

array([ 5, 33, 42, 10,  0, 13, 30, 11, 37, 34, 21, 26, 44, 19,  4, 46, 18,  6, 23, 22, 14, 47,  7,
       41, 32,  2, 17, 36, 39, 16, 15, 35, 43,  3, 24, 29, 31, 48, 12, 38, 25,  9,  8, 49,  1, 28,
       40, 45, 27, 20], dtype=int64)

In [64]:
state_name[state_count_sorted]


array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
       'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
       'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
       'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69')

In [65]:
state_count[state_count_sorted]

array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
        216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
         84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
         25,   24,   17,   16,   10], dtype=int64)

In [66]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

In [67]:
str_data[:,5] = np.where(str_data[:,5] == '' , 0 , str_data[:,5])
str_data[:,5] = np.where(np.isin(str_data[:,5], states_west) , 1 , str_data[:,5])
str_data[:,5] = np.where(np.isin(str_data[:,5], states_south) , 2 , str_data[:,5])
str_data[:,5] = np.where(np.isin(str_data[:,5], states_midwest) , 3 , str_data[:,5])
str_data[:,5] = np.where(np.isin(str_data[:,5], states_east) , 4 , str_data[:,5])

In [68]:
np.unique(str_data[:,5] , return_counts = True)

(array(['0', '1', '2', '3', '4'], dtype='<U69'),
 array([ 500, 2467, 3384, 1733, 1916], dtype=int64))

## Converting to Numbers

In [69]:
str_data

array([['0', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['0', '1', '36', '10', '1', '4'],
       ...,
       ['9', '1', '36', '5', '1', '1'],
       ['9', '1', '36', '17', '1', '3'],
       ['9', '1', '36', '4', '0', '3']], dtype='<U69')

In [70]:
str_data = str_data.astype(np.int32)

In [71]:
str_data

array([[ 0,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 0,  1, 36, 10,  1,  4],
       ...,
       [ 9,  1, 36,  5,  1,  1],
       [ 9,  1, 36, 17,  1,  3],
       [ 9,  1, 36,  4,  0,  3]])

### Checkpoint 1: Strings

In [72]:
checkpoint_str = checkpoint('Checkpoint-str' , header_str , str_data)

In [73]:
checkpoint_str['data']

array([[ 0,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 0,  1, 36, 10,  1,  4],
       ...,
       [ 9,  1, 36,  5,  1,  1],
       [ 9,  1, 36, 17,  1,  3],
       [ 9,  1, 36,  4,  0,  3]])

In [74]:
checkpoint_str['header']

array(['issue date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

## 6. Manipulating Numeric Columns

In [75]:
num_data

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [76]:
np.isnan(num_data).sum()

0

### Substitute "Filler" Values

In [77]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### ID

In [78]:
temporary_fill

68616520.0

In [79]:
np.isin(num_data,temporary_fill).sum()

8005

#### Temporary Stats

In [80]:
review[:, num_col_index]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

#### Funded Amount

In [81]:
num_col_index

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [82]:
num_data[:,2] = np.where(num_data[:,2] == temporary_fill, 
                                  review[0, num_col_index[2]],
                                  num_data[:,2])
num_data[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [83]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### Loaned Amount, Interest Rate, Total Payment, Installment

In [84]:
for i in [1,3,4,5]:
    num_data[:,i] = np.where(num_data[:,i] == temporary_fill, 
                                  review[2, num_col_index[i]],
                                  num_data[:,i])


In [85]:
num_data

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

In [86]:
str_data[:,0]

array([0, 0, 0, ..., 9, 9, 9])

In [87]:
str_data

array([[ 0,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 0,  1, 36, 10,  1,  4],
       ...,
       [ 9,  1, 36,  5,  1,  1],
       [ 9,  1, 36, 17,  1,  3],
       [ 9,  1, 36,  4,  0,  3]])

In [88]:
header_str

array(['issue date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

### Currency Change

#### The Exchange Rate

In [89]:
EUR_USD =np.genfromtxt('EUR-USD.csv', delimiter=',', autostrip =True ,  skip_header = 1 , usecols = 3)
EUR_USD 

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [90]:
exchange_rate = str_data[:,0]
exchange_rate

array([0, 0, 0, ..., 9, 9, 9])

In [91]:

for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i-1],
                             exchange_rate)    
exchange_rate = np.where(exchange_rate == 0,
                    np.mean(EUR_USD),
                    exchange_rate) 

In [92]:
exchange_rate

array([1.11, 1.11, 1.11, ..., 1.13, 1.13, 1.13])

In [93]:
np.unique(exchange_rate)

array([1.06, 1.08, 1.09, 1.09, 1.1 , 1.1 , 1.11, 1.11, 1.12, 1.12, 1.13, 1.13, 1.13])

In [94]:
exchange_rate.shape

(10000,)

In [95]:
num_data.shape

(10000, 6)

In [96]:
exchange_rate = exchange_rate.reshape(10000,1)

In [97]:
num_data = np.hstack((num_data , exchange_rate))

In [98]:
num_data

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.11],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.11],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.13],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.13],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.13]])

In [99]:
header_num = np.concatenate((header_num , np.array(['exchange_rate'])))

In [100]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

#### From USD to EUR

In [101]:
columns_dollar = np.array([1,2,4,5])

In [102]:
num_data[:,columns_dollar]

array([[35000.  , 35000.  ,  1184.86,  9452.96],
       [30000.  , 30000.  ,   938.57,  4679.7 ],
       [15000.  , 15000.  ,   494.86,  1969.83],
       ...,
       [10000.  , 10000.  ,  1372.97,  2185.64],
       [35000.  , 10000.  ,   354.3 ,  3199.4 ],
       [10000.  , 10000.  ,   309.97,   301.9 ]])

In [103]:
a = num_data[:,1] / num_data[:,6]
a.reshape(10000,  1)

array([[31654.54],
       [27132.46],
       [13566.23],
       ...,
       [ 8884.2 ],
       [31094.7 ],
       [ 8884.2 ]])

In [104]:
for i in columns_dollar:
    num_data = np.hstack((num_data, np.reshape(num_data[:,i] / num_data[:,6], (10000,1))))

In [105]:
num_data

array([[48010226.  ,    35000.  ,    35000.  , ...,    31654.54,     1071.61,     8549.4 ],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13566.23,      447.56,     1781.54],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8884.2 ,     1219.77,     1941.77],
       [46154151.  ,    35000.  ,    10000.  , ...,     8884.2 ,      314.77,     2842.41],
       [66055249.  ,    10000.  ,    10000.  , ...,     8884.2 ,      275.38,      268.21]])

#### Expanding the header

In [106]:
header_additional = np.array([column_name + '_EUR' for column_name in header_num[columns_dollar]])

In [107]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [108]:
header_num = np.concatenate((header_num , header_additional))

In [109]:
header_num[columns_dollar] =  np.array([column_name + '_USD' for column_name in header_num[columns_dollar]])

In [110]:
header_num

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [111]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [112]:
header_num = header_num[columns_index_order]
header_num

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [113]:
num_data = num_data[:, columns_index_order]

In [114]:
num_data

array([[48010226.  ,    35000.  ,    31654.54, ...,     9452.96,     8549.4 ,        1.11],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13566.23, ...,     1969.83,     1781.54,        1.11],
       ...,
       [50415990.  ,    10000.  ,     8884.2 , ...,     2185.64,     1941.77,        1.13],
       [46154151.  ,    35000.  ,    31094.7 , ...,     3199.4 ,     2842.41,        1.13],
       [66055249.  ,    10000.  ,     8884.2 , ...,      301.9 ,      268.21,        1.13]])

### Interest Rate

In [115]:
header_num

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [116]:
num_data[:,5]  = num_data[:,5]/100

In [117]:
num_data[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

### Checkpoint 2: Numeric

In [118]:
checkpoint_numeric = checkpoint('Checkpoint-numeric' , header_num ,num_data)

In [119]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31654.54, ...,     9452.96,     8549.4 ,        1.11],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13566.23, ...,     1969.83,     1781.54,        1.11],
        ...,
        [50415990.  ,    10000.  ,     8884.2 , ...,     2185.64,     1941.77,        1.13],
        [46154151.  ,    35000.  ,    31094.7 , ...,     3199.4 ,     2842.41,        1.13],
        [66055249.  ,    10000.  ,     8884.2 , ...,      301.9 ,      268.21,        1.13]]))

## 7. Creating the "Complete" Dataset

In [130]:
checkpoint_numeric['header']

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [134]:
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [121]:
checkpoint_str['data'].shape

(10000, 6)

In [123]:
checkpoint_numeric['data'].shape

(10000, 11)

In [128]:
loan_data = np.hstack((checkpoint_numeric['data'] , checkpoint_str['data']))

In [129]:
loan_data

array([[48010226.  ,    35000.  ,    31654.54, ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13566.23, ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8884.2 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31094.7 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     8884.2 , ...,        4.  ,        0.  ,        3.  ]])

In [133]:
header_full = np.concatenate((checkpoint_numeric['header'] , checkpoint_str['header']))

## 8. Sorting the New Dataset

In [139]:
np.argsort(loan_data[:,0])

array([2086, 4812, 2353, ..., 4935, 9388, 8415], dtype=int64)

In [141]:
np.sort(loan_data[:,0])

array([  373332.,   575239.,   707689., ..., 68614880., 68615915., 68616519.])

In [142]:
loan_data[2086]

array([373332.  ,   9950.  ,   9038.08,   1000.  ,    908.35,      0.18,    360.97,    327.89,
         1072.82,    974.5 ,      1.1 ,     10.  ,      1.  ,     36.  ,     21.  ,      0.  ,
            1.  ])

In [140]:
loan_data[np.argsort(loan_data[:,0])]

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    11080.08, ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     9083.5 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5170.7 , ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3553.68, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19745.42, ...,        3.  ,        0.  ,        2.  ]])

In [143]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [144]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    11080.08, ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     9083.5 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5170.7 , ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3553.68, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19745.42, ...,        3.  ,        0.  ,        2.  ]])

In [145]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

## 9. Storing the New Dataset

In [147]:
loan_data = np.vstack((header_full , loan_data))

In [148]:
np.savetxt('loan-data-processed' , loan_data , fmt='%s' , delimiter=',')